/* eslint-disable */ 
// File autogenerated by npm run buildSceneTemplates. Do not modify.
const sceneSetupTemplate = {
    "metadata": {
        "action1": "Leave"
    },
    "setup": "\r\nWhen the smoke dissipated, her hands started shaking so bad the revolver fell to the mud.\r\n\r\n\"You did good, {{playerName}},\" said the minister, jumping out of the stage coach and looking around. \"You saved us both from these brigands.\"\r\n\r\n\"They weren't brigands,\" {{playerName}} said, getting up and cleaning her clothes as best as she could.\r\n\r\n\"They're gone now, that's what matters. But this road is still not safe. Not for two stranded travelers like us.\"\r\n\r\n\"What do you propose?\" {{playerName}} took the revolver and didn't even attempt to return it back to the minister.\r\n\r\n\"You should go and get help, of course! There should be an inn not too far from here. The driver told me I could... refreshen there,\" the minister said, pointing at his flask, almost empty by now.\r\n\r\n\"I see.\"\r\n\r\n\"If you go now, you'll arrive before sunset.\"\r\n\r\n\"What will you do, minister?\"\r\n\r\n\"I'll wait here. It's not like I could be of any help to you. Just be sure to send help my way when you find it.\"\r\n"
};
export default sceneSetupTemplate;
