/* eslint-disable */ 
// File autogenerated by npm run buildSceneTemplates. Do not modify.
const sceneSetupTemplate = {
    "metadata": {
        "title": "The stage coach",
        "actions": {
            "Alys opened the door and jumped out": {
                "sideEffect": {
                    "loot": {
                        "weapons": {
                            "revolver": {
                                "type": "revolver",
                                "damage": "1-2",
                                "skill": "aim",
                                "ammunitionType": "bullets",
                                "ammunition": "6-6"
                            }
                        }
                    }
                },
                "goTo": "./outsideTheStageCoach"
            }
        }
    },
    "setup": "\r\n\"Alys it is, then,\" the minister said and then the driver anounced they were parting.\r\n\r\nNow he snored, reeking of booze, and Alys glanced at the woods.\r\n\r\n\"Why here?\" she muttered. \"Why now?\"\r\n\r\nThe horses neighed at once and the driver shouted. More voices outside, and then the dry bark of a rifle. The driver slided off his box and hit the ground with a thud. It was the middle of nowhere.\r\n\r\nAlys heart raced in her chest and the minister awoke at once. He looked almost serene.\r\n\r\n\"Told you this road wasn's safe, didn't I?\" he said. As Alys looked frantically at the other side of the window, trying to understand what the voices were saying over the neighing of the horses, the minister rummaged through his belongins until he found a black box.\r\n\r\n\"Now, take this,\" he said, opening the box and handing Alys a revolver.\r\n\r\n\"What? No, you take it\".\r\n\r\n\"Listen, Alys, this is the only thing that's going to keep you alive today. I'm too drunk to save us both, so it's up to you.\"\r\n\r\nThe minster held the gun and Alys, reluctantly, took it. It was cold and greasy.\r\n\r\n\"I'll wait for you here,\" the minister said as he opened the door.\r\n"
};
export default sceneSetupTemplate;
