/* eslint-disable */
// File autogenerated by npm run buildSceneTemplates. Do not modify.
const sceneSetupTemplate = {
    metadata: {
        title: 'Lady Cartwright',
        actions: {
            'Alys opened the door and jumped out': {
                sideEffect: {
                    loot: {
                        weapons: {
                            revolver: {
                                type: 'revolver',
                                damage: '1-2',
                                skill: 'aim',
                                ammunitionType: 'bullets',
                                ammunition: '6-6',
                            },
                        },
                    },
                },
                goTo: './outsideTheStageCoach',
            },
        },
    },
    setup:
        '\n"Such an honor, milady," the minister said with, bowing slightly.\n\nNow he snored, reeking of booze, and Lady Cartwright glanced at the woods.\n\n"Why here?" she muttered. "Why now?"\n\nThe horses neighed at once and the driver shouted. More voices outside, and then the dry bark of a rifle. The driver slided off his box and hit the ground with a thud. It was the middle of nowhere.\n\nLady Cartwright heart raced in her chest and the minister awoke at once. He looked almost serene.\n\n"Told you this road wasn\'s safe, didn\'t I, milady?" he said. As Lady Cartwright looked frantically at the other side of the window, trying to understand what the voices were saying over the neighing of the horses, the minister rummaged through his belongins until he found a black box.\n\n"Now, take this," he said, opening the box and handing Lady Cartwright a revolver.\n\n"What? No, you take it".\n\n"Listen, Lady Cartwright, this is the only thing that\'s going to keep you alive today. I\'m too drunk to save us both, so it\'s up to you."\n\nThe minster held the gun and Lady Cartwright, reluctantly, took it. It was cold and greasy.\n\n"I\'ll wait for you here," the minister said as he opened the door.\n',
};
export default sceneSetupTemplate;
