/* eslint-disable */ 
// File autogenerated by npm run buildSceneTemplates. Do not modify.
const sceneSetupTemplate = {
    "metadata": {
        "title": "The stage coach",
        "actions": {
            "She raised the revolver": {
                "goTo": "./combat"
            }
        }
    },
    "setup": "\r\nThe sun was still up, but it was cold. It had rained the day before and the road was muddy.\r\n\r\nIn front of the stage coach, {{playerName}} could see the driver laying motionless on the mud. In front of the horses, two men advanced towards the stage coach, guns ready.\r\n\r\n\"Hey, you there!\" shouted one of them, taller, with a scar on his left eye.\r\n\r\n\"Is it her?\" asked the other, but his companion didn't answer. Intead, he took a new bullet from his pocket and proceeded to reload the rifle.\r\n\r\n{{playerName}} felt the thumping of her heart and could barely breath. However, she knew what was going to happen to her if she froze like that.\r\n"
};
export default sceneSetupTemplate;
