/* eslint-disable */ 
// File autogenerated by npm run buildSceneTemplates. Do not modify.
const sceneSetupTemplate = {
    "metadata": {
        "action1": "\"Alys.\"",
        "action2": "\"Lady Cartwright.\""
    },
    "setup": "\r\nThe stage coach rumbled softly over the packed dirt of the path.\r\n\r\n**The damsel** looked at the dark woods at the other side of the windows. Between her hands, a letter she had read just once, yet it was already worn out.\r\n\r\nThe stage coach was for her only, except for the **drunken minister** who snored beside her.\r\n\r\n\"A dangerous road this one,\" he had said at the beginning of the journey, already dizzy and sipping from a flask he kept close to his heart. The damsel had nodded, but the minister was insistent.\r\n\r\n\"Nobody knows what lies ahead, so I'd rather face the unknown with someone whose name I can cry in fear, don't you think?\"\r\n"
};
export default sceneSetupTemplate;
