/* eslint-disable */
// File autogenerated by npm run buildSceneTemplates. Do not modify.
const sceneSetupTemplate = {
    metadata: {
        title: 'The road',
    },
    setup: '\nA dirty trail extended into the distance.\n',
};
export default sceneSetupTemplate;
